### ISSUE TITLE
This link is broken: http://new.bombono.org/download/revo/REVO_Eksplika.zip 

### ISSUE THREAD

**Issue by RichardJECooke** [muravjov/vkompililo#1]
And there is no EO link under: "Links to REVO dictionaries"

:(

**Comment by muravjov** [comment]
Thank you, I fixed the links; for example, http://new.bombono.org/download/revo/REVO_Eksplika.tar.gz .

All other links are at the very bottom.

**Comment by muravjov** [comment]
I want to note, that people complain about failures in ColorDict & Android 5 (I have Android 4).
If you have problems, open a new issue :)
